[package]
name = "mimp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "4.5.7", features = ["derive"] }
anyhow = "1.0.86"
env_logger = "0.11.3"
log = "0.4.21"
hickory-resolver = "0.24.1"
